# Change these first
owner: kgh6265 # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Graphic Design Club Website
    url: $GDWEBSITE_RAW
  - name: Graphic Design Club Domain
    url: https://gdclub.ritdubai.ae
  - name: Graphic Design Club Admin Panel
    url: $GDADMIN_RAW
  - name: Graphic Design Club Admin Panel Domain
    url: https://admin.gdclub.ritdubai.ae

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "RIT Dubai Graphic Design Club Status"
  introTitle: "Keep an eye on our essential systems that power the Graphic Design Club."
  introMessage: This is a status page which uses **real-time** data to keep track of our essential web services. Powered by Upptime.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://gdclub.ritdubai.ae
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
